### ISSUE TITLE
Events missing Spring 2021 webinar

### ISSUE THREAD

**Issue by etanttila** [apluslms/apluslms.github.io#5]
The page for the spring 2021 webinar (https://wiki.aalto.fi/display/EDIT/Aplus+development+webinar+4.6.2021) is not created yet and missing from the listing of events.

**Comment by etanttila** [comment]
Likewise the page for the summer 2021 webinar (https://wiki.aalto.fi/display/EDIT/Aplus+summer+webinar+20.8.2021) is missing. It would be good to have these webinars listed on the events page, and the pages to have the link to the Panopto playlist as well as the presentation slides.

**Comment by markkuriekkinen** [comment]
Added in the commit 504d82706782a683de030a02a960719e18afe166
